const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
module.exports=async({mainWindow,origin,dataDir,BrowserWindow})=>{
  const checks=[],wait=ms=>new Promise(r=>setTimeout(r,ms));
  const get=()=>fetch(origin+'/api/state').then(r=>r.json());
  const post=async(endpoint,data)=>{const r=await fetch(origin+'/api/'+endpoint,{method:'POST',headers:{Origin:origin,'X-Tarkov-Local':'1','Content-Type':'application/json'},body:JSON.stringify(data)});assert.equal(r.status,200);};
  const until=async(fn)=>{for(let i=0;i<100;i++){if(await fn())return;await wait(100);}throw Error('Smoke test timed out');};
  const js=code=>mainWindow.webContents.executeJavaScript(code);
  await until(()=>js("document.getElementById('connectionDot').classList.contains('connected')"));
  let state=await get();assert.equal(state.profiles.length,0);assert.equal(state.settings.autoScreenshotEnabled,false);assert.equal(state.settings.screenshotCleanupEnabled,false);checks.push('blank profile; capture and cleanup disabled');
  await until(async()=>!!(await get()).runtime.overlay?.ready);
  assert.equal((await get()).runtime.overlay.focusable,false);checks.push('packaged native overlay worker ready, keyboard focus disabled');
  const overlayPage=new BrowserWindow({show:false,width:720,height:620,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});
  try{
    await overlayPage.loadURL(origin+'/?overlay=1');
    await until(()=>overlayPage.webContents.executeJavaScript("document.getElementById('connectionDot').classList.contains('connected')"));
    assert.equal(await overlayPage.webContents.executeJavaScript("getComputedStyle(document.querySelector('.map-hud')).display"),'none');
    checks.push('overlay position status panel hidden');
    await overlayPage.webContents.executeJavaScript("document.getElementById('overlayAutoShot').click()");
    await until(()=>js("document.getElementById('toggleAutoShot').getAttribute('aria-pressed')==='true'"));
    assert.equal((await get()).settings.autoScreenshotEnabled,true);
    await until(()=>fs.existsSync(path.join(dataDir,'state.json')) && JSON.parse(fs.readFileSync(path.join(dataDir,'state.json'),'utf8')).settings.autoScreenshotEnabled===true);
    await js("document.getElementById('toggleAutoShot').click()");
    await until(()=>overlayPage.webContents.executeJavaScript("document.getElementById('overlayAutoShot').getAttribute('aria-pressed')==='false'"));
    assert.equal((await get()).runtime.autoScreenshot.phase,'off');
    await until(()=>JSON.parse(fs.readFileSync(path.join(dataDir,'state.json'),'utf8')).settings.autoScreenshotEnabled===false);
    for(const width of [360,720]){
      overlayPage.setSize(width,620);
      await wait(100);
      assert.ok(await overlayPage.webContents.executeJavaScript("(()=>{const b=document.getElementById('overlayAutoShot').getBoundingClientRect(),c=document.getElementById('hideOverlay').getBoundingClientRect();return b.width>0 && b.left>=0 && b.right<=innerWidth && c.right<=innerWidth;})()"));
    }
    checks.push('overlay auto screenshot switch synchronizes both ways, persists and stops worker; narrow toolbar fits');
    await overlayPage.webContents.executeJavaScript("document.getElementById('overlayFollow').click()");
    await until(()=>js("!document.getElementById('followPlayer').checked"));assert.equal((await get()).settings.followPlayer,false);
    checks.push('overlay follow switch synchronizes to main window and disk');
    const profile='aaaaaaaaaaaaaaaaaaaaaaaa',folder=path.join(dataDir,'Logs','log_smoke');fs.mkdirSync(folder);
    const stamp=(at,text)=>new Date(at).toISOString().replace('T',' ').replace('Z',' +00:00')+'|1.1.5.1|Info|application|'+text+'\n';
    const now=Date.now()-1000;
    fs.writeFileSync(path.join(folder,'application_000.log'),stamp(now,'Session mode: Pve')+stamp(now+1,'SelectedProfile ProfileId:'+profile)+stamp(now+2,'scene preset path:maps/sandbox_start_preset.bundle'));
    await until(async()=>(await get()).selectedProfile===profile);
    const catalog=await fetch(origin+'/api/catalog').then(r=>r.json());
    const quest=catalog.tasks.find(q=>!q.disabled && q.objectives.some(o=>o.zones?.some(z=>z.map?.id==='653e6760052c01c1c805532f' && z.position)));
    assert.ok(quest,'ground zero task fixture');
    await post('progress',{id:quest.id,status:'active'});
    await js("document.getElementById('autoFloor').checked=false");
    const before=await js("document.getElementById('mapStage').style.transform");
    fs.writeFileSync(path.join(dataDir,'Screenshots','2026-10-04[12-00]_102.30, 2.96, -5.91_0.0, 0.0, 0.0, 1.0 (0).png'),'test');
    await until(async()=>(await get()).runtime.position?.x===102.3);await wait(300);
    assert.equal(await js("document.getElementById('mapStage').style.transform"),before);checks.push('screenshot moves player without recentering when follow disabled');
    await js("document.getElementById('followPlayer').click()");
    await until(()=>overlayPage.webContents.executeJavaScript("document.getElementById('overlayFollow').getAttribute('aria-pressed')==='true'"));
    assert.notEqual(await js("document.getElementById('mapStage').style.transform"),before);checks.push('follow re-enable centers immediately and synchronizes');
    const taskSelector=JSON.stringify('[data-task="'+quest.id+'"]');
    await js('document.querySelector('+taskSelector+').click()');
    await until(()=>js("document.querySelectorAll('.marker').length>0"));
    await post('progress',{id:quest.id,status:'completed'});
    await until(()=>js("document.querySelectorAll('.marker').length===0"));checks.push('selected completed task marker disappears');
    await post('progress',{id:quest.id,status:'ready'});await wait(150);assert.equal(await js("document.querySelectorAll('.marker').length"),0);checks.push('ready-to-submit task marker stays hidden');
    await mainWindow.reload();await until(()=>js("document.getElementById('connectionDot').classList.contains('connected')"));
    assert.equal(await js("document.getElementById('followPlayer').checked"),true);checks.push('renderer reload succeeds with persisted settings');
    assert.ok(await js("document.querySelector('.brand').textContent.includes('leaf0329')"));
    await js("document.getElementById('settingsButton').click()");
    assert.equal(await js("document.querySelectorAll('[data-directory]').length"),2);
    assert.equal(await js("document.querySelector('#settingsForm button[type=submit]').textContent"),'保存全部设置');
    await js("document.getElementById('cleanupScreenshots').click();document.getElementById('autoShotInterval').value=13;document.getElementById('overlayOpacity').value=65");
    state=await get();assert.equal(state.settings.screenshotCleanupEnabled,false);assert.equal(state.settings.overlayOpacity,100);
    await js("document.getElementById('closeSettings').click();document.getElementById('settingsButton').click()");
    assert.equal(await js("document.getElementById('cleanupScreenshots').checked"),false);
    await js("document.getElementById('autoShotInterval').value=13;document.getElementById('overlayOpacity').value=65;document.getElementById('saveSettings').click()");
    await until(async()=>(await get()).settings.overlayOpacity===65);
    assert.equal((await get()).settings.autoScreenshotInterval,13);assert.equal((await get()).runtime.overlay.opacity,65);
    checks.push('branding, native picker controls, draft cancellation and unified save; native opacity 65%');
    await overlayPage.webContents.executeJavaScript("document.getElementById('overlayOpacityQuick').value=80;document.getElementById('overlayOpacityQuick').dispatchEvent(new Event('change'))");
    await until(async()=>(await get()).runtime.overlay.opacity===80);checks.push('overlay quick opacity slider applies to the native window');
    await post('progress',{id:quest.id,status:'active'});
    await until(()=>overlayPage.webContents.executeJavaScript('!!document.querySelector('+taskSelector+')'));
    await overlayPage.webContents.executeJavaScript('document.querySelector('+taskSelector+').click();document.getElementById("detailContent").scrollTop=100000');
    const geometry=await overlayPage.webContents.executeJavaScript("(()=>{const p=document.getElementById('detailPanel').getBoundingClientRect(),b=document.getElementById('closeDetail').getBoundingClientRect(),d=document.getElementById('detailContent');return {scrolled:d.scrollTop>0,visible:b.top>=p.top && b.bottom<=p.bottom};})()");
    assert.ok(geometry.scrolled);assert.ok(geometry.visible);checks.push('overlay details scroll independently; close button stays visible');
    overlayPage.showInactive();await wait(400);
    fs.writeFileSync(path.join(dataDir,'overlay-detail.png'),(await overlayPage.webContents.capturePage()).toPNG());
    await overlayPage.webContents.executeJavaScript("document.getElementById('closeDetail').click()");
    assert.equal(await overlayPage.webContents.executeJavaScript("document.getElementById('detailPanel').hidden"),true);
  }finally{overlayPage.destroy();}
  return checks;
};
